### ISSUE TITLE
current sensing issue?

### ISSUE THREAD

**Issue by tyler78** [BrainFPV/betaflight#11]
Using v3.1.6-BRAIN-3 firmware, re-1, and mPB with default options for the current sensor (Onboard ADC, 250 scale, 0 offset).  I'm seeing values that are dynamic in the 0.16 to 0.2A range while disarmed, but it always stays in the range while flying- clearly not realistic.... Didn't see this issue reported anywhere and there's always a chance the board is bad or I have something setup incorrectly....

**Comment by mluessi** [comment]
This sounds like a hardware problem. Please contact support@brainfpv.com
