### ISSUE TITLE
Transponder not supported on BrainRE1

### ISSUE THREAD

**Issue by Zethyl** [BrainFPV/betaflight#12]
The betaflight configurator indicates that the transponder is not supported on the board (BrainRE1). This is the only feature keeping me from going on Betaflight with this board, everything else seems to work.

**Comment by mluessi** [comment]
RE1 uses a different transponder system, which you will need to configure using the OSD menu or CLI. Both I-Lap and Trackmate are supported when using RE1 with Betaflight.
