### ISSUE TITLE
IR Transponder not reporting correctly in ilap

### ISSUE THREAD

**Issue by Zethyl** [BrainFPV/betaflight#13]
I was able to try out the IR transponder at a MultiGP event recently. We were able to "scan in" my transponder without issue and ilap saw the transponder during a race when passing receiver. There are a few issues that I noticed:

- ilap ID that is set in betaflight CLI is not the same number as seen by the ilap receiver, very confusing because you dont know what your ID is until you "scan in"
- ilap ID that is set in betaflight CLI has a different number of characters than what is seen when scanned in
- ilap receiver / PC software shows something like 9999 each time transponder passes receiver during a race

**Comment by mluessi** [comment]
Do you still have this problem?
