### ISSUE TITLE
Wraith32V2 DSHOT1200 Motor 2 issue

### ISSUE THREAD

**Issue by RoadyFPV** [BrainFPV/betaflight#19]
I changed Lumenier 30A ESC to Wraith32V2 35A.

Motor 2 will not spin with DSHOT1200. With DSHOT600 all works fine. 
When i go to the motor tab and select only motor 2  it works fine. When i select all Motors togeher (Master slider) then Motor 2 will not work only 1 3 4 works fine. when Master slider goes from 1100 to zero ESC 2 beep 2 tones. (arming beep?)
All esc min throttle 1000 and max 2000.

**Comment by mluessi** [comment]
DSHOT1200 is more sensitive to noise than DSHO600, which is most likely the source of your problem. I recommend to just use DSHOT600. The difference won't be noticeable. Compared to DSHOT600, DSHOT1200 reduces the response time of your quad by about 13 micro seconds, which is about 0.1% of the overall response time.
