### ISSUE TITLE
Smart Audio - Cant change settings via OSD

### ISSUE THREAD

**Issue by RoadyFPV** [BrainFPV/betaflight#22]
Hi i cant change Smart Audio Values via OSD.
OSD displays only  -- - - --- -- -- -
Flashed back to 3.2.4 all is fine.

I use UART6 for Smart Audio.

**Comment by mluessi** [comment]
Unfortunately SmartAudio is no longer supported on UART6. Can you use UART1?

**Comment by RoadyFPV** [comment]
Yes,
i solder it to UART1 and it works fine.
Why dont work on UART6?

**Comment by mluessi** [comment]
Because of the inverter. It was originally working but there were a bunch of changes in BF that made it incompatible. We would have to add workarounds for those changes, which is difficult to support in the long term, so it's better to just use UART1 and not support SA on UART6

**Comment by RoadyFPV** [comment]
Ok my problem is solved. I use UART1

**Comment by mluessi** [comment]
Perfect :)

**Comment by tgreer** [comment]
@mluessi this makes wiring a real mess having to switch. ie UART1 for Reciever is perfect, and using UART6 TX for SmartAudio just makes wiring clean.
