### ISSUE TITLE
Where are the tlfw files?

### ISSUE THREAD

**Issue by joeynuggetz** [BrainFPV/betaflight#23]
Been trying to flash a BF upgrade via dRonin as I have no luck accomplishing this via the BF configurator as I do not have access to the boot pins but I only see .hex files.

**Comment by SuTeCH007** [comment]
Simple flash .hex via BF. You do not need a boot pin to boot into DFU.

**Comment by joeynuggetz** [comment]
Doesn't seem to work for me. If I enter DFU on the CLI it never looks like the board enters DFU mode.
