### ISSUE TITLE
v3.5.4-BRAIN-1 - no osd in Configurator: 10.5.0, works in 10.4, guess we need a fw4?

### ISSUE THREAD

**Issue by yosemitez** [BrainFPV/betaflight#27]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Please note that feature requests are not 'fire and forget'. It is a lot more likely that the feature you would like to have will be implemented if you keep watching your feature request, and provide more details to developers looking into implementing your feature, and help them with testing.

**Comment by mluessi** [comment]
10.5.0 is not intended to be used with betaflight 3.5. Please use 10.4.0 with BF 3.5.4

**Comment by yosemitez** [comment]
copy that
