### ISSUE TITLE
Radix and Configurator Freeze when activating Telemetry

### ISSUE THREAD

**Issue by RoadyFPV** [BrainFPV/betaflight#28]
By flashing the 4.0 to the Radix (clean flash) connect to the configurator, activate Telemetry hit save and reboot, now the Radix and Configurator freeze. When i unplug the Radix from USB the Configurator works again.

only way to fix, is short the boot pads and flash 4.0 again

**Comment by FPVRaven** [comment]
I have same issue, as soon as i enable telemetry and hit save everything freezes.....After that even driver fixer freeze as well, plug in lipo = freeze as well. The led next to the usb become static red and the one after it does blink.
BTW i have a R9 and R9 mini, both flashed with the latest flex firmware (eulbt firmware),  i hope this helps :)

**Comment by RoadyFPV** [comment]
I tried it with Crossfire and Jeti ExBus, both with the same result.

**Comment by mluessi** [comment]
Thanks for the report. I'm looking into it

**Comment by zakre256** [comment]
I had the same issue and I had to jumper the boot pad and reflash the firmware. Tried numerous different things to prevent it but activating telemetry in config, freezes/fake bricks the board. So I left it off and no problems so far

**Comment by mluessi** [comment]
This has been fixed in 4.0.0-RC5-BRAIN-1. Please try the latest release

**Comment by RoadyFPV** [comment]
Ok the freeze is gone! Thx
But i have an other question. Why outputs the buzzer a permanent tone when u arm and have motor stop enabled?
The old version of the buzz was not so annoying ;)
