### ISSUE TITLE
Betaflight 4.0 RC6 CPU overlaod

### ISSUE THREAD

**Issue by FPVRaven** [BrainFPV/betaflight#29]
Hey there, RC6 does not work with RPM Filter (Radix FC), my quad freaked out while try to hover! 
Seems like something overloading the CPU: 

# tasks
Task list             rate/hz  max/us  avg/us maxload avgload     total/ms
00 - (         SYSTEM)     10       2       1    0.5%    0.5%         0
01 - (         SYSTEM)    801    2292       2  184.0%    0.6%        36
02 - (       GYRO/PID)   3206      99      85   32.2%   27.7%      4476
05 - (             RX)     32      76      48    0.7%    0.6%        24
06 - (         SERIAL)     98     118       1    1.6%    0.5%        31
07 - (       DISPATCH)    801       4       0    0.8%    0.0%         7
08 - (BATTERY_VOLTAGE)     49       3       1    0.5%    0.5%         1
09 - (BATTERY_CURRENT)     49      17       1    0.5%    0.5%         0
10 - ( BATTERY_ALERTS)      5       2       1    0.5%    0.5%         0
11 - (         BEEPER)     98      29       1    0.7%    0.5%         1
15 - (      TELEMETRY)    245      96       1    2.8%    0.5%       325
20 - (        VTXCTRL)      5      32      12    0.5%    0.5%         1
21 - (        CAMCTRL)      5       1       1    0.5%    0.5%         0
23 - (    ADCINTERNAL)      2       2       0    0.5%    0.0%         0
24 - (       PINIOBOX)     19       2       0    0.5%    0.0%         0
RX Check Function                   3       2                         1
Total (excluding SERIAL)                       225.2%   32.9%
BrainFPV tasks remaining stacks:
main: 0 Bytes free
idle: 80 Bytes free
Betaflight: 1168 Bytes free
OSD: 712 Bytes free

Running 4K/4K gyro/pid looptimes, also running latest blheli_32 test firmware. Same settings and ESC firmware works fine with 2 other flightcontrollers, got to be some firmware bug. After reflashing the same issue was there, seems like there is no workarround for this one :( 

Edit: Just checked RC5 = 
# tasks
Task list             rate/hz  max/us  avg/us maxload avgload     total/ms
00 - (         SYSTEM)     11       2       0    0.5%    0.0%         0
01 - (         SYSTEM)    801    2298       2  184.5%    0.6%        13
02 - (       GYRO/PID)   3206      77      68   25.1%   22.3%       522
05 - (             RX)     31      68      32    0.7%    0.5%         3
06 - (         SERIAL)     98     120       1    1.6%    0.5%         1
08 - (BATTERY_VOLTAGE)     48       2       1    0.5%    0.5%         0
09 - (BATTERY_CURRENT)     48       1       1    0.5%    0.5%         0
10 - ( BATTERY_ALERTS)      8       2       0    0.5%    0.0%         0
11 - (         BEEPER)     98      14       1    0.6%    0.5%         0
20 - (        VTXCTRL)      8       1       0    0.5%    0.0%         0
21 - (        CAMCTRL)      8       1       0    0.5%    0.0%         0
23 - (    ADCINTERNAL)      6       2       0    0.5%    0.0%         0
24 - (       PINIOBOX)     19       1       1    0.5%    0.5%         0
RX Check Function                   3       2                         0
Total (excluding SERIAL)                       214.9%   25.4%
BrainFPV tasks remaining stacks:
main: 0 Bytes free
idle: 80 Bytes free
Betaflight: 2752 Bytes free
OSD: 728 Bytes free

Same there but this was stock nothing changed at all...

Ok tested 3.5.7 = 
# tasks
Task list             rate/hz  max/us  avg/us maxload avgload     total/ms
00 - (         SYSTEM)      9       2       0    0.5%    0.0%         0
01 - (         SYSTEM)    801    2242       2  180.0%    0.6%        14
02 - (       GYRO/PID)   3205      51      45   16.8%   14.9%       534
03 - (            ACC)    801      22      16    2.2%    1.7%        63
04 - (       ATTITUDE)     96       9       7    0.5%    0.5%         3
05 - (             RX)     32      41      37    0.6%    0.6%         6
06 - (         SERIAL)     96     101       1    1.4%    0.5%         2
08 - (BATTERY_VOLTAGE)     49       2       1    0.5%    0.5%         0
09 - (BATTERY_CURRENT)     49       1       0    0.5%    0.0%         0
10 - ( BATTERY_ALERTS)      4       2       1    0.5%    0.5%         0
11 - (         BEEPER)     97      14       1    0.6%    0.5%         0
13 - (           BARO)     43      21      12    0.5%    0.5%         2
14 - (       ALTITUDE)     39       4       3    0.5%    0.5%         0
20 - (        VTXCTRL)      4       1       0    0.5%    0.0%         0
21 - (        CAMCTRL)      4       1       0    0.5%    0.0%         0
23 - (    ADCINTERNAL)      0       2       0    0.5%    0.0%         0
24 - (       PINIOBOX)     19       2       1    0.5%    0.5%         0
RX Check Function                   2       1                         0
Total (excluding SERIAL)                       205.7%   21.3%
BrainFPV tasks remaining stacks:
main: 0 Bytes free
idle: 80 Bytes free
Betaflight: 1688 Bytes free
OSD: 800 Bytes free
 
After a lot of testing i found one serious issue and one thing witch confuses me and i can`t find anything about that online. 

The CPU load is same even in 3.5.7 stable, it is caused by SD card and logging, removing sd card brings it down to 50%, disable BBlogging completly brings it below 30%. 

However i allways get wrong looptimes in the "tasks command" even on 2k/2k it will show = 
01 - (         SYSTEM)    801    
02 - (       GYRO/PID)   3205
Betaflight devs say we need to watch GYRO/PID and check if it is the right numbers, it never is with 
my Radix....  

Update: 

After two days of testing i can fly now, i reinstalled the ESC, the configurator and the firmware, then i removed SD card and disable logging (can`t really tell why it flipped on the first test but well i works now!).....Test flight was fine but i have no logging, please fix this, we need logging for 4.0 to get a solide tune ;) Also the wrong looptimes are still there....

**Comment by mluessi** [comment]
I assume it is because of the 4k/4k setting. Please try with having it set to 8k/8k

**Comment by FPVRaven** [comment]
Just checked 8k/8k = 
# tasks
Task list             rate/hz  max/us  avg/us maxload avgload     total/ms
00 - (         SYSTEM)     10       2       1    0.5%    0.5%         0
01 - (         SYSTEM)    801    2293       4  184.1%    0.8%        26
02 - (       GYRO/PID)   3206     104      95   33.8%   30.9%      1458
05 - (             RX)     32      90      54    0.7%    0.6%        10
06 - (         SERIAL)     98     117       1    1.6%    0.5%         5
07 - (       DISPATCH)    801       3       1    0.7%    0.5%         2
08 - (BATTERY_VOLTAGE)     49       2       2    0.5%    0.5%         0
09 - (BATTERY_CURRENT)     49      19       2    0.5%    0.5%         0
10 - ( BATTERY_ALERTS)      6       2       1    0.5%    0.5%         0
11 - (         BEEPER)     98      21       3    0.7%    0.5%         0
15 - (      TELEMETRY)    245     112       1    3.2%    0.5%        61
20 - (        VTXCTRL)      6      33       4    0.5%    0.5%         0
21 - (        CAMCTRL)      6       1       0    0.5%    0.0%         0
23 - (    ADCINTERNAL)      4       3       0    0.5%    0.0%         0
24 - (       PINIOBOX)     19       2       0    0.5%    0.0%         0
RX Check Function                   3       2                         0
Total (excluding SERIAL)                       227.2%   36.3%
BrainFPV tasks remaining stacks:
main: 0 Bytes free
idle: 80 Bytes free
Betaflight: 1168 Bytes free
OSD: 728 Bytes free 

Same :/

**Comment by FPVRaven** [comment]
I just saw the stable release, however there is nothing fixed, looptimes are wrong, cpu overloaded or the stats in % are bugged if like to log...... there was corrupt log stuff in my older logs as well, could you please start fixing this stuff?! I am allready getting really dissapointed about the firmware for Radix (can`t belive the should be a stable firmware) :( How can it be stable if the tasks are completely wrong? there are older discussions about this as well, these are basic things we need to check for save flying guys, this is really not what i expected........I will try stable release but i have still this = 

# tasks
Task list             rate/hz  max/us  avg/us maxload avgload     total/ms
00 - (         SYSTEM)     10       1       1    0.5%    0.5%         0
01 - (         SYSTEM)    801    2300       1  184.7%    0.5%        17
02 - (       GYRO/PID)   3205      95      81   30.9%   26.4%      1299
05 - (             RX)     32      76      48    0.7%    0.6%         9
06 - (         SERIAL)     98     191       1    2.3%    0.5%         6
07 - (       DISPATCH)    801       6       0    0.9%    0.0%         2
08 - (BATTERY_VOLTAGE)     49       2       1    0.5%    0.5%         0
09 - (BATTERY_CURRENT)     49       2       1    0.5%    0.5%         0
10 - ( BATTERY_ALERTS)      6       2       1    0.5%    0.5%         0
11 - (         BEEPER)     98       2       1    0.5%    0.5%         0
15 - (      TELEMETRY)    245      99       0    2.9%    0.0%        78
20 - (        VTXCTRL)      6      32       4    0.5%    0.5%         0
21 - (        CAMCTRL)      6       1       0    0.5%    0.0%         0
23 - (    ADCINTERNAL)      4       2       0    0.5%    0.0%         0
24 - (       PINIOBOX)     19       1       0    0.5%    0.0%         0
RX Check Function                   2       2                         0
Total (excluding SERIAL)                       224.6%   30.5%
BrainFPV tasks remaining stacks:
main: 0 Bytes free
idle: 80 Bytes free
Betaflight: 1168 Bytes free
OSD: 728 Bytes free

I will try to fly with log, impossible to have that high load, maybe a bug or it will cook my cpu.......

**Comment by mluessi** [comment]
It must have something to do with your settings. Please type "diff defaults" in the CLI in betaflight and post the output here

**Comment by RoadyFPV** [comment]
I have the problem too. Clean flash, tasks in cli show every time around 4k. In settings, PID/Gyro 2k/2k...  4k/4k... 8k/8k... 

Tasks shows around 4k on all 3 settings.
I think on 3.5.7 too.

**Comment by mluessi** [comment]
@RoadyFPV please post the output of "diff defaults" in the CLI. Without that it's difficult to help.

**Comment by FPVRaven** [comment]
Hold on i think i can give the data you need, i know exacly what is causing this and where it is comming from ;) 
I can say that it got nothing to do with the settings, only with logging, but i asume it is a bug since it would not fly at all with 220% cpu load and more, i tested it and it fly, first flip over was caused by changes on the board orientation in config (was able to reproduce this and a friend had it as well).....

My testing => 

1. with SD-card and logging enabled (logging rate does not matter , 1k and 4k tested)

# tasks
Task list             rate/hz  max/us  avg/us maxload avgload     total/ms
00 - (         SYSTEM)     10       2       0    0.5%    0.0%         0
01 - (         SYSTEM)    800    2299       2  184.4%    0.6%        40
02 - (       GYRO/PID)   3207      95      82   30.9%   26.7%      4437
05 - (             RX)     32      82      48    0.7%    0.6%        25
06 - (         SERIAL)     98     117       1    1.6%    0.5%         3
07 - (       DISPATCH)    800       3       1    0.7%    0.5%         8
08 - (BATTERY_VOLTAGE)     49       2       1    0.5%    0.5%         1
09 - (BATTERY_CURRENT)     49       2       1    0.5%    0.5%         0
10 - ( BATTERY_ALERTS)      5       2       1    0.5%    0.5%         0
11 - (         BEEPER)     98       2       1    0.5%    0.5%         1
15 - (      TELEMETRY)    245      98       1    2.9%    0.5%       335
20 - (        VTXCTRL)      5      33       7    0.5%    0.5%         0
21 - (        CAMCTRL)      5       1       0    0.5%    0.0%         0
23 - (    ADCINTERNAL)      2       2       1    0.5%    0.5%         0
24 - (       PINIOBOX)     19       2       1    0.5%    0.5%         0
RX Check Function                   3       2                         1
Total (excluding SERIAL)                       224.1%   32.4%
BrainFPV tasks remaining stacks:
main: 0 Bytes free
idle: 80 Bytes free
Betaflight: 1168 Bytes free
OSD: 720 Bytes free

2. same settings only SD-card removed

# tasks
Task list             rate/hz  max/us  avg/us maxload avgload     total/ms
00 - (         SYSTEM)     10       2       0    0.5%    0.0%         0
01 - (         SYSTEM)    801     369       1   30.0%    0.5%        66
02 - (       GYRO/PID)   3206     115      99   37.3%   32.2%      1388
05 - (             RX)     32      89      56    0.7%    0.6%         9
06 - (         SERIAL)     98     240       1    2.8%    0.5%         7
07 - (       DISPATCH)    801       4       1    0.8%    0.5%         2
08 - (BATTERY_VOLTAGE)     49       2       1    0.5%    0.5%         0
09 - (BATTERY_CURRENT)     49       2       1    0.5%    0.5%         0
10 - ( BATTERY_ALERTS)      6       2       1    0.5%    0.5%         0
11 - (         BEEPER)     98      18       1    0.6%    0.5%         0
15 - (      TELEMETRY)    245     117       1    3.3%    0.5%        84
20 - (        VTXCTRL)      6      22       3    0.5%    0.5%         0
21 - (        CAMCTRL)      6       1       0    0.5%    0.0%         0
23 - (    ADCINTERNAL)      4       3       0    0.5%    0.0%         0
24 - (       PINIOBOX)     19       2       1    0.5%    0.5%         0
RX Check Function                   5       2                         0
Total (excluding SERIAL)                        76.7%   37.3%
BrainFPV tasks remaining stacks:
main: 0 Bytes free
idle: 80 Bytes free
Betaflight: 1168 Bytes free
OSD: 720 Bytes free

3. again same settings with logging disabled and SD-card removed 

# tasks
Task list             rate/hz  max/us  avg/us maxload avgload     total/ms
00 - (         SYSTEM)     11       2       0    0.5%    0.0%         0
01 - (         SYSTEM)    801       2       1    0.6%    0.5%         2
02 - (       GYRO/PID)   3206      90      81   29.3%   26.4%      1178
05 - (             RX)     32      56      48    0.6%    0.6%         8
06 - (         SERIAL)     98     116       1    1.6%    0.5%         1
07 - (       DISPATCH)    801       3       0    0.7%    0.0%         2
08 - (BATTERY_VOLTAGE)     49       2       1    0.5%    0.5%         0
09 - (BATTERY_CURRENT)     49       1       1    0.5%    0.5%         0
10 - ( BATTERY_ALERTS)      7       2       1    0.5%    0.5%         0
11 - (         BEEPER)     98       2       1    0.5%    0.5%         0
15 - (      TELEMETRY)    245      93       0    2.7%    0.0%        44
20 - (        VTXCTRL)      7      32       3    0.5%    0.5%         0
21 - (        CAMCTRL)      7       1       0    0.5%    0.0%         0
23 - (    ADCINTERNAL)      5       2       0    0.5%    0.0%         0
24 - (       PINIOBOX)     20       1       1    0.5%    0.5%         0
RX Check Function                   3       2                         0
Total (excluding SERIAL)                        38.4%   30.5%
BrainFPV tasks remaining stacks:
main: 0 Bytes free
idle: 80 Bytes free
Betaflight: 1264 Bytes free
OSD: 728 Bytes free

02 -  should show correct looptimes, 01 - should not go that high on cpu load
maybe like this (example from my aikon f4 @ 4k/4k with logging enabled "onboard logging") => 


01 - (         SYSTEM)   1000      22       3    2.7%    0.8%        42
02 - (       GYRO/PID)   4001      91      76   36.9%   30.9%      158


My settings => 
# diff all

# version
# Betaflight / RADIX (RADIX) 4.0.0 Apr 16 2019 / 10:15:22 (7a09137a3) MSP API: 1.41

# start the command batch
batch start

# reset configuration to default settings
defaults nosave

board_name RADIX
manufacturer_id 
mcu_id 004c004f3237510835333639
signature 

# name
name SkyHogRC_Radix

# resources
resource MOTOR 2 A10
resource MOTOR 3 A03

# timer

# dma

# mixer
mixer CUSTOM
mmix 0  1.000 -0.880  1.000 -1.000
mmix 1  1.000 -0.880 -1.000  1.000
mmix 2  1.000  0.880  1.000  1.000
mmix 3  1.000  0.880 -1.000 -1.000

# servo

# servo mix


# feature
feature TELEMETRY

# beeper
beeper -DISARMING
beeper -ARMING
beeper -ARMING_GPS_FIX
beeper -GPS_STATUS
beeper -ACC_CALIBRATION
beeper -ACC_CALIBRATION_FAIL
beeper -READY_BEEP
beeper -DISARM_REPEAT
beeper -ARMED
beeper -ON_USB
beeper -BLACKBOX_ERASE
beeper -CRASH_FLIP
beeper -CAM_CONNECTION_OPEN
beeper -CAM_CONNECTION_CLOSE
beeper -RC_SMOOTHING_INIT_FAIL

# beacon

# map

# serial
serial 0 8192 115200 57600 0 115200
serial 5 32 115200 57600 0 115200

# led

# color

# mode_color

# aux
aux 0 0 0 1600 2100 0 0
aux 1 13 1 1700 2100 0 0
aux 2 26 1 900 1300 0 0

# adjrange

# rxrange

# vtx

# rxfail

# display_name

# master
set gyro_lowpass_hz = 0
set gyro_lowpass2_type = PT1
set gyro_lowpass2_hz = 150
set dyn_notch_width_percent = 0
set dyn_notch_q = 250
set dyn_notch_min_hz = 60
set dyn_lpf_gyro_min_hz = 0
set dyn_lpf_gyro_max_hz = 0
set acc_hardware = NONE
set baro_hardware = NONE
set min_check = 1005
set max_check = 1995
set rssi_channel = 7
set rc_smoothing_derivative_hz = 150
set rc_smoothing_input_type = PT1
set rc_smoothing_derivative_type = PT1
set fpv_mix_degrees = 25
set serialrx_provider = SBUS
set airmode_start_throttle_percent = 20
set blackbox_p_ratio = 32
set blackbox_device = NONE
set dshot_bidir = ON
set motor_pwm_rate = 32000
set align_board_yaw = 180
set vbat_scale = 121
set ibata_scale = 167
set frsky_vfas_precision = 1
set osd_units = IMPERIAL
set osd_tim1 = 2561
set osd_vbat_pos = 2497
set osd_rssi_pos = 2105
set osd_tim_1_pos = 2519
set osd_tim_2_pos = 33
set osd_flymode_pos = 65
set osd_crosshairs_pos = 205
set osd_current_pos = 2507
set osd_mah_drawn_pos = 2488
set osd_craft_name_pos = 362
set osd_warnings_pos = 2313
set osd_avg_cell_voltage_pos = 2476
set osd_core_temp_pos = 410
set osd_stat_rtc_date_time = ON
set osd_stat_tim_1 = ON
set osd_stat_tim_2 = OFF
set osd_stat_max_spd = OFF
set osd_stat_endbatt = ON
set osd_stat_battery = ON
set debug_mode = GYRO_SCALED
set scheduler_optimize_rate = ON
set vtx_channel = 4
set vtx_power = 3
set vtx_freq = 5800
set vcd_video_system = PAL
set gyro_1_sensor_align = DEFAULT
set gyro_rpm_notch_harmonics = 1
set rpm_notch_lpf = 100

# profile
profile 0

set dyn_lpf_dterm_min_hz = 100
set dyn_lpf_dterm_max_hz = 200
set dterm_lowpass2_hz = 0
set anti_gravity_gain = 10000
set feedforward_transition = 30
set iterm_relax = RPY
set iterm_relax_type = GYRO
set iterm_relax_cutoff = 11
set p_pitch = 48
set i_pitch = 69
set f_pitch = 80
set p_roll = 44
set i_roll = 69
set f_roll = 80
set p_yaw = 37
set i_yaw = 105
set f_yaw = 80
set abs_control_gain = 2
set d_min_roll = 27
set d_min_pitch = 29
set d_min_boost_gain = 35

# profile
profile 1


# profile
profile 2


# restore original profile selection
profile 0

# rateprofile
rateprofile 0

set roll_rc_rate = 120
set pitch_rc_rate = 120
set yaw_rc_rate = 120
set roll_expo = 20
set pitch_expo = 20
set yaw_expo = 20
set roll_srate = 72
set pitch_srate = 72
set yaw_srate = 72

# rateprofile
rateprofile 1


# rateprofile
rateprofile 2


# rateprofile
rateprofile 3


# rateprofile
rateprofile 4


# rateprofile
rateprofile 5


# restore original rateprofile selection
rateprofile 0

# save configuration
save

I used these settings for all 3 "tasks".......i hope this helps to find the problem here :)

**Comment by mluessi** [comment]
Please try a different sdcard or re-format your card. I tried your settings with an sdcard inserted and it works fine. I assume it may be trying to read or format the card and keeps failing

**Comment by FPVRaven** [comment]
Ok thank you for checking it, allmoast got crazy with it, log was crazy noisy, maybe cpu load was real and pids or filters was not able to work correct......
I got a Kingston 2GB in there, i have only big ones over for testing, i can test samsung evo 32gb, sandisk ultra 32gb and sandisk ultra 64gb, can i find somewhere witch ones are supported for sure? Never had this Problem because i allways had onboard logging before :/ 

sandisk extreme sd 32gb =>
# tasks
Task list             rate/hz  max/us  avg/us maxload avgload     total/ms
00 - (         SYSTEM)     10       2       1    0.5%    0.5%         0
01 - (         SYSTEM)    801    2131     366  171.1%   29.8%      2079
02 - (       GYRO/PID)   2406      92      81   22.6%   19.9%      1036
05 - (             RX)     32      82      49    0.7%    0.6%        10
06 - (         SERIAL)     96     236       1    2.7%    0.5%         4
07 - (       DISPATCH)    801       3       0    0.7%    0.0%         3
08 - (BATTERY_VOLTAGE)     49       2       2    0.5%    0.5%         0
09 - (BATTERY_CURRENT)     49       2       1    0.5%    0.5%         0
10 - ( BATTERY_ALERTS)      6       2       1    0.5%    0.5%         0
11 - (         BEEPER)     96      15       1    0.6%    0.5%         0
15 - (      TELEMETRY)    228      99       1    2.7%    0.5%        58
20 - (        VTXCTRL)      6      43       3    0.5%    0.5%         0
21 - (        CAMCTRL)      6       1       0    0.5%    0.0%         0
23 - (    ADCINTERNAL)      4       2       0    0.5%    0.0%         0
24 - (       PINIOBOX)     19       1       1    0.5%    0.5%         0
RX Check Function                   2       2                         0
Total (excluding SERIAL)                       202.4%   54.3%
BrainFPV tasks remaining stacks:
main: 0 Bytes free
idle: 80 Bytes free
Betaflight: 1168 Bytes free
OSD: 752 Bytes free

fresh formated card, now gyro and looptime even more incorrect, what is going on there.....

sandisk ultra 32gb => 

# tasks
Task list             rate/hz  max/us  avg/us maxload avgload     total/ms
00 - (         SYSTEM)      9       2       1    0.5%    0.5%         0
01 - (         SYSTEM)    801    2122       2  170.4%    0.6%        66
02 - (       GYRO/PID)   3206      98      81   31.9%   26.4%      9860
05 - (             RX)     32      84      48    0.7%    0.6%        55
06 - (         SERIAL)     98     264       1    3.0%    0.5%        61
07 - (       DISPATCH)    801       6       0    0.9%    0.0%        17
08 - (BATTERY_VOLTAGE)     49       3       1    0.5%    0.5%         2
09 - (BATTERY_CURRENT)     49       2       0    0.5%    0.0%         1
10 - ( BATTERY_ALERTS)      5       3       2    0.5%    0.5%         0
11 - (         BEEPER)     98      17       1    0.6%    0.5%         3
15 - (      TELEMETRY)    245     102       0    2.9%    0.0%       739
20 - (        VTXCTRL)      5      36       7    0.5%    0.5%         1
21 - (        CAMCTRL)      5       1       0    0.5%    0.0%         0
23 - (    ADCINTERNAL)      1      16       1    0.5%    0.5%         0
24 - (       PINIOBOX)     19       3       1    0.5%    0.5%         0
RX Check Function                   3       2                         2
Total (excluding SERIAL)                       211.4%   31.1%
BrainFPV tasks remaining stacks:
main: 0 Bytes free
idle: 80 Bytes free
Betaflight: 1168 Bytes free
OSD: 728 Bytes free

i really need to know what card i can use, same with all of my cards (fromated).....

**Comment by FPVRaven** [comment]
Finally i found the bug, the shown faliue is wrong, just type in "tasks" for a second time and it will go down to the correct valiue, maybe this is fixabel, if not am at least sure it is just a bug witch shows wrong valiues everytime you type tasks for the first time......

# tasks
Task list             rate/hz  max/us  avg/us maxload avgload     total/ms
00 - (         SYSTEM)     10       2       1    0.5%    0.5%         0
01 - (         SYSTEM)    801    2291       2  184.0%    0.6%       204
02 - (       GYRO/PID)   3206      71      61   23.2%   20.0%      1090
05 - (             RX)     32      68      39    0.7%    0.6%         8
06 - (         SERIAL)     98     107       1    1.5%    0.5%         5
08 - (BATTERY_VOLTAGE)     49       6       2    0.5%    0.5%         0
09 - (BATTERY_CURRENT)     49       1       1    0.5%    0.5%         0
10 - ( BATTERY_ALERTS)      6       6       1    0.5%    0.5%         0
11 - (         BEEPER)     98      14       1    0.6%    0.5%         0
15 - (      TELEMETRY)    245      92       0    2.7%    0.0%        58
20 - (        VTXCTRL)      6      24       3    0.5%    0.5%         0
21 - (        CAMCTRL)      6       1       0    0.5%    0.0%         0
23 - (    ADCINTERNAL)      4       2       0    0.5%    0.0%         0
24 - (       PINIOBOX)     19       5       0    0.5%    0.0%         0
RX Check Function                   2       1                         0
Total (excluding SERIAL)                       215.2%   24.2%
BrainFPV tasks remaining stacks:
main: 0 Bytes free
idle: 80 Bytes free
Betaflight: 1168 Bytes free
OSD: 728 Bytes free

# tasks
Task list             rate/hz  max/us  avg/us maxload avgload     total/ms
00 - (         SYSTEM)     10       1       0    0.5%    0.0%         0
01 - (         SYSTEM)    801       4       2    0.8%    0.6%       211
02 - (       GYRO/PID)   3206      72      60   23.5%   19.7%      1969
05 - (             RX)     32      43      39    0.6%    0.6%        14
06 - (         SERIAL)     98     754       1    7.8%    0.5%         6
08 - (BATTERY_VOLTAGE)     49       6       1    0.5%    0.5%         0
09 - (BATTERY_CURRENT)     49       1       0    0.5%    0.0%         0
10 - ( BATTERY_ALERTS)      5       2       1    0.5%    0.5%         0
11 - (         BEEPER)     98       1       1    0.5%    0.5%         1
15 - (      TELEMETRY)    246       1       0    0.5%    0.0%        59
20 - (        VTXCTRL)      5       1       2    0.5%    0.5%         0
21 - (        CAMCTRL)      5       1       0    0.5%    0.0%         0
23 - (    ADCINTERNAL)      2       2       0    0.5%    0.0%         0
24 - (       PINIOBOX)     19       1       1    0.5%    0.5%         0
RX Check Function                   2       2                         0
Total (excluding SERIAL)                        29.9%   23.4%
BrainFPV tasks remaining stacks:
main: 0 Bytes free
idle: 80 Bytes free
Betaflight: 1168 Bytes free
OSD: 720 Bytes free

My SD card is no issue as well it works, just a confusing bug (was to simple to type in tasks for a second time, so it took me some time to find that out) :D 

Greetings SkyHogRC
