### ISSUE TITLE
Can not connect RC to FC

### ISSUE THREAD

**Issue by Cactusdave** [BrainFPV/betaflight#30]
After I flashed the new Betaflight 4.0 I can not get my radio controller to my FC. FC is a Radix and the FC is a Frsky DX9.  Radio is bound but no response in betaflight.
Thank you for any advice.

**Important: This is not the right place to get help with configuration issues. Your issue will be closed without further comment.**

Please get help from other user support options such as asking the manufacturer of the hardware you are using, RCGroups: https://rcgroups.com/forums/showthread.php?t=2464844, or Slack (registration at https://slack.betaflight.com/) or other user support forums & groups (e.g. Facebook).

**Comment by mluessi** [comment]
Did you copy-paste your old settings by any chance?
