### ISSUE TITLE
Radix target not appearing in list

### ISSUE THREAD

**Issue by evilC** [BrainFPV/betaflight#31]
I have a Radix LI and I am attempting to upgrade to BF 4.0.2-BRAIN-1  
When I use the firmware flasher in BF configurator, and select `Load Firmware [Local]`, and point it at `betaflight_v4.0.2-BRAIN-1_RADIX.hex`, I see no Radix target in the list:  
![](https://i.imgur.com/dADTiiN.gif)  
Note, for some reason the screen recording puts my cursor in the wrong place, I really am clicking the load local ;)  
Please advise...

**Comment by OGFPV** [comment]
It will not show up in the list of "online FW" because it is locally stored on your PC. Just click the "Flash Firmware" button to begin the install.

**Comment by evilC** [comment]
Ahh, it looks like it was maybe a glitch in the configurator
Even though I started a fresh configurator, clicked load local, I was still seeing this on that page:  

https://i.imgur.com/32VDpLN.gif  
Notice how it has "Target: Omnibus", but "Local file loaded" is also showing at bottom of page
This lead me to believe it was going to flash Omnibus
