### ISSUE TITLE
gOSD Artificial Horizon shown steps should be a different option to max steps

### ISSUE THREAD

**Issue by evilC** [BrainFPV/betaflight#33]
Personally as an acro flyer, I love having an artificial horizon, it helps immensely if messing around with camera up-tilt, as you always have the AHI to tell you when you are level, regardless of camera up-tilt angle. However, the configuration option for it seems kind of pointless.  

There is currently only one option for the Artificial Horizon - "ARTIFICIAL HORIZON STEPS"  
I have no idea why anyone would want anything other than 9 - what use-case is there for the default setting of 2? Why would you want to stop being informed of current pitch angle at 20deg pitch? Surely the more pitch you are at, the more critical it gets to know how far from level you are?  
For me, any option >1 starts to over-write other OSD elements at the top or bottom of the screen, but setting it to 1 just makes things worse, as you stop being informed of pitch rate at >10deg.  
IMHO, there needs to be two new options (You could even just remove the existing option, hard-wire it to 9, and just add these two new options instead):  

HORIZON VERTICAL SIZE  
Seeing as you do not appear to be able to resize the OSD element in BF, you need an option to limit the vertical size of the AHI, to stop it over-writing other OSD elements above and below it.  

HORIZON STEP SIZE
You should be able to configure how many pixels there are between each 10deg step of the ladder, such that if I limit the VERTICAL_SIZE option above, I can still control how many 10deg steps are visible within that limited window.  
This would also potentially allow the user to configure it such that the step size matches the FOV of their camera, such that if you nosed down 10deg, then the 0deg ladder line would line up with the horizon.  

[Edited to add] I am a coder, and would potentially be willing to attempt to implement this myself (Although I usually do C# rather than C). Would I need any special hardware to enable me to develop this myself? If I did manage to implement this, would you be amenable to merging a PR with these changes?

**Comment by ItsMeAubey** [comment]
Bump
