### ISSUE TITLE
Betaflight 4.1

### ISSUE THREAD

**Issue by azixaka** [BrainFPV/betaflight#34]
Are you planning to release a Betaflight 4.1 based firmware any time soon?

**Comment by haslinghuis** [comment]
Looks like schedule is 2 weeks behind original.

**Comment by azixaka** [comment]
But it is happening and it's already great! I bought the FC yesterday now waiting for 4.1 as all my quads are on 4.1 and don't even want to try without the RPM filtering. :)

**Comment by haslinghuis** [comment]
Me too have to wait. But you can try RC6 if you want to. Just download the hex files from assets here and flash with local file option. I finished my build yesterday and did just that.

**Comment by haslinghuis** [comment]
You can find betaflight 4.1 here: https://github.com/BrainFPV/betaflight/releases. Off course be aware it is not official yet.

**Comment by pregeeth** [comment]
@azixaka In my opinion, its worth the wait :) Also RC6 is available for testing.

**Comment by azixaka** [comment]
I have three quads, three different setups - frames, escs, motors.

I have lots of flights logged with Matek F722 SE, Mini and CL Racing F7 and SP Racing H7 Ex, all on the same track.

It will be so interesting to see how Radix works in the same conditions. Have very high expectations of it as this is the least functional apart from OSD but the most expensive FC on the market. It's also F4 ;)

**Comment by azixaka** [comment]
How is it going guys? Where is our 4.1? :)

**Comment by haslinghuis** [comment]
Because of special functions (like graphical OSD and Bosch gyro) + having a company (BrainFPV) who wants to have stable tested firmware - we will have to wait a little longer than the original version of Betaflight without those gimmicks. Give it a week or so. But you do not have to wait - it is already here - (see link above) and flash using local file button to your Radix and go?

**Comment by haslinghuis** [comment]
@azixaka It is here! You can close this issue now ;-)

**Comment by azixaka** [comment]
My Radix is defective, has been RMA'ed just now. I won't get to test it soon what a pity. :)

But yeah, great!
