### ISSUE TITLE
gyro_calib_duration = 0 error in CLI

### ISSUE THREAD

**Issue by Near76** [BrainFPV/betaflight#49]
I receive the following error in the CLI after upgrading to BF 4.2.0 from BrainFPV support page.  I am not sure if it affecting performance, but noticed the error and am not sure if or what I should do next.  Thank you.
'''# 
# get gyro_calib_duration
gyro_calib_duration = 0
###ERROR: get: CORRUPTED CONFIG: gyro_calib_duration = 0###
Allowed range: 50 - 3000
Default value: 125'''

**Comment by haslinghuis** [comment]
Flash with `full chip erase` and don't import an older `diff`

**Comment by Near76** [comment]
All set, thanks!
