### ISSUE TITLE
Feature Request:  Better BetaFlight OSD support

### ISSUE THREAD

**Issue by cbehrends** [BrainFPV/betaflight#5]
As a OSD user, it would be cool if I had full Betaflight control over the OSD layouts. 
While the current feature set is nice for sure, some options such as adding/removing the various horizon bars simply do not function in Betaflight.  It would be nice to have just the Crosshairs and the single artificial horizon without the graduated incline bars.

My FatShark Teleporters get hard to view the OSD with too many things happening on the screen.

Great product, I love where this is going.  (a Piko version would be cool for my 90mm build ;)

**Comment by cbehrends** [comment]
@mluessi I'm reading up on the OSD code and may take a shot at extending it / enhancing it.  If I have any success I'll let you know.

**Comment by mluessi** [comment]
@cbehrends the OSD is fully configurable using the configurator. The AHI just doesn't have the bars because it's not needed IMO. You can enable the center mark; it's called crosshairs.

In general, I don't think we should add a lot of OSD features that are not present in regular betaflight. I would make the fork harder to maintain and we would need a separate version of the configurator.

**Comment by cbehrends** [comment]
@mluessi It may be that I'm simply mistaken, I'll take another look.  But to me it appeared that the behavior I'm describing is a feature of regular Betaflight that the RE1 doesn't fully support.  I agree that there should not be any non standard Betaflight elements in the OSD.  At the same time, it would be nice if the RE1's behavior matched that of the Betaflight configurator.

Thanks for responding!  Reading the code has actually been pretty easy...it's well written.

Edit:

I found this description of the Betaflight OSD elements on Propwashed.com

Attitude Elements
Crosshairs – This is a static display element that is constantly drawn to your video display. On airplanes, an OSD element like this is useful for establishing a “glide point” when landing in FPV. I’m not sure why you would want it for quadcopters – possibly for setting a horizon reference for training to fly at certain speeds?

Artificial Horizon – This is a bar that is drawn across the center of your field of view. It is always drawn so that the bar is flat and level with the horizon. This can be useful for flying up high or in the dark where you might not always have a ground reference.

Horizon Sidebars – These are fixed display elements that show you the upper and lower bounds of the artificial horizon described above. With these you can measure how many degrees your quadcopter is pitched up or down.

The RE1 has the 'Sidebars' in the center of your FOV and the 'Sidebars' and 'Artificial Horz' are tied together as a single element.

**Comment by cbehrends** [comment]
A little more research and I think I see where my confusion lies.  The RE1 is not using a 'standard' Betaflight OSD, but a vector graphics one (which is bad ass by the way).  The OSD I'm used to in Betaflight does not quite look the same as the Taulabs/Dronin one that this implementation uses.  That being said, all of the elements are there and working fine.  It appears it would be a matter of matching the Betaflight look/feel and separating the toggling of the 'Horiz' and 'Sidebar' elements.  Just for nerdiness, I'm going to take a stab at it.  My OCD side screams at me when my layouts don't match :D 

I respect your opinion that you don't feel the sidebar feature is needed and will not submit any PR's.

Thanks again for a great product!
