### ISSUE TITLE
Passive buzzer support?

### ISSUE THREAD

**Issue by kh4** [BrainFPV/betaflight#6]
I just reflashed from dRonin and sorted out motor ordering et all, Everything is working but it seems BF version is lacking support for driving a passive buzzer?? or I am simply blind.

**Comment by mluessi** [comment]
Do you mean a buzzer that needs a 4kHz AC drive? That's correct, very few people use these buzzers so I didn't add it initially, but I can add it.

**Comment by kh4** [comment]
Yeah, exactly. I happen to have some buzzers salvaged from cheap Lipo voltage alarms (like the HK 2-8S one) which need a 4kHz (or so) signal to drive them.

It would be nice to have direct support for them.

**Comment by kh4** [comment]
Ah I can see it is really easy to add for RE1 since it is just one bit in FPGA config reg, coolness ;)

**Comment by kh4** [comment]
Hacked it up and compiled a firmware for AC style buzzer.

https://github.com/kh4/betaflight/commit/184fa9343f8db57b9516906b2680d263c6cc207d

Firmware binaries if someone wants to use this too

http://kari.hautio.net/brain/betaflight_3.1.5_BRAINRE1-ACBZ.hex
http://kari.hautio.net/brain/betaflight_3.1.5_BRAINRE1-ACBZ.tlfw

**Comment by kh4** [comment]
I guess this is about the proper way to do it, it would be only in CLI though. I have not tested this though as I only have one brainRe1 board.
https://github.com/kh4/betaflight/commit/87ea7f8c24bc7c14b133b04938f2ce49bcb41953

**Comment by mluessi** [comment]
Thanks :). I'm not sure if I would add it to the betaflight beeper config, as RE1 is the only FC that can do it. So it may make more sense to include it in the RE1 config. I also avoid changing the EEPROM version, as it will create conflicts when merging in betaflight. I can include your changes and move the config, it that works for you.

**Comment by kh4** [comment]
Yes, it makes sense to have it in RE1 config. I was also looking for a way to avoid bumping EEPROM.

If using RE1 config it makes sense to set it in FPGA init which avoids changing any beeper code.

There is no hurry as I am happily flying with the modified firmware mentioned in earlier commit.

**Comment by mluessi** [comment]
Sounds good. It should be fine without bumping the EEPROM version, as it uses a CRC and adding a new field to the config pretty much guarantees that the CRC check will fail and the config will be initialized with defaults.
