### ISSUE TITLE
BF 3.1.6 JETIEXBUS

### ISSUE THREAD

**Issue by RoadyFPV** [BrainFPV/betaflight#8]
How to conect JETIEXBUS to UART3. And how can i disable Bidirectional mode?
I do not want to break anything.

thx RoadyFPV

**Comment by mluessi** [comment]
It seems like the JETIEXBUS opens the UART in RXTX mode, which isn't supported on UART3 on RE1. Did you have it working with earlier versions? I added code to prevent this type of configuration on UART3 as it isn't supported, but it seems like the JETIEXBUS hangs as it doesn't check for errors.

**Comment by RoadyFPV** [comment]
I fly BF 3.1.5 with JETIEXBUS, this works fine. But when i select JetiEXBus in 3.1.6  than i cant connect to re1.

**Comment by mluessi** [comment]
OK, I realized that the check I added isn't actually needed. Please try this version: https://github.com/BrainFPV/betaflight/releases/tag/v3.1.6-BRAIN-2

**Comment by RoadyFPV** [comment]
Thx for ur fast help. I will try it tomorrow and give a feedback.

**Comment by RoadyFPV** [comment]
Hi mluessi,

i try the new version. But when i select SerialRX and JetiexBus i cant connect to re1. Plug in USB and no com port detect.

**Comment by RoadyFPV** [comment]
I see when i load the new firmware in dronin it say 3.1.6Brain1 but i select your new file Brain2

sorry for my bad english

**Comment by RoadyFPV** [comment]
@mluessi 
have u n idea why i cant connect to re1 after i select jetiexbus? i flashd the brain2 again but with the same result. wen i selct sbus i can connect. but is the wrong protocol

**Comment by mluessi** [comment]
Can you try 3.1.6-BRAIN-2 again? It's possible that the .tlfw file wasn't rebuilt properly and I just rebuilt and uploaded it again.

**Comment by RoadyFPV** [comment]
I loaded the .tlfw file again and flashd with the same result. when i select jetiexbus i cant connect to re1.
I plugd in usb windows detect usb with sound but the second detect sound will not come. after this no com port detect and windows will bring a massage that the usb device is not workd correctly.

**Comment by RoadyFPV** [comment]
Hi 
i try to flash the betaflight hex file on my re1 because the tlfw file wont work. but without success. is it even possible to flash hex file on re1?

**Comment by RoadyFPV** [comment]
@mluessi 
can u pls upload the new 3.1.6 tlfw file for me? i  would like to use 3.1.6 but i cant.

**Comment by mluessi** [comment]
@RoadyFPV I'm looking into it; there were changes introduced in Betaflight 3.1.6 that are causing problems with RE1. Namely, JETIEXBUS configures the serial port to also send data to the receiver, which isn't supported UART3 on RE1. For now, use either 3.1.5 or connect the receiver to UART1.

I will let you know once I have a fix that you can test. Later this week, hopefully.

**Comment by RoadyFPV** [comment]
ok
thank you very much. but i use tbs smartaudio on uart1. so i will wait and use 3.1.5. enter the osd menu from stats screen is very nice in 3.1.6.

**Comment by mluessi** [comment]
@RoadyFPV please try this version: https://drive.google.com/open?id=0ByA776HMnh4gRERUT1ZDb3hrSUk

**Comment by RoadyFPV** [comment]
@mluessi
this works, i can use jetiexbus. testflight come later, configuration is fine. thank you.

**Comment by RoadyFPV** [comment]
@mluessi 
Test flight was successful. Thanks for ur great work i'am so happy.
Greetings
